name: thermal_printer_app
description: A Flutter app for connecting to thermal receipt printers via Bluetooth
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.12.9
  permission_handler: ^11.0.1
  esc_pos_utils: ^1.1.0
  image: ^3.3.0
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
